services:
    # Repository
    api.repository.calendar:
        class: ApiBundle\Repository\CalendarRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - ApiBundle\Entity\Calendar

    api.repository.room_type:
        class: ApiBundle\Repository\RoomTypeRepository
        factory: ["@doctrine.orm.default_entity_manager", getRepository]
        arguments:
            - ApiBundle\Entity\RoomType

    # Helpers
    api.helper.date:
        class: ApiBundle\Helper\DateHelper

    # Managers
    api.manager.calendar:
        class: ApiBundle\Manager\CalendarManager
        arguments:
            - "@doctrine.orm.entity_manager"

    # Services
    api.service.calendar:
        class: ApiBundle\Service\CalendarService
        arguments:
            - "@api.manager.calendar"
            - "@api.repository.calendar"
            - "@api.helper.date"

    # Validators
    api.validator.date_range:
        class: ApiBundle\Validator\DateRangeValidator
        arguments:
            - "@validator"
