<?php

namespace ApiBundle\Repository;

use ApiBundle\Entity\Calendar;

/**
 * CalendarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendarRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get the Calendar by Date Range
     *
     * @param \DateTime $from
     * @param \DateTime $to
     * @return Calendar[]
     */
    public function findByDateRange(\DateTime $from, \DateTime $to)
    {
        $qb = $this->createQueryBuilder('c')
            ->where('c.day BETWEEN :from AND :to')
            ->setParameter('from', $from)
            ->setParameter('to', $to);

        return $qb->getQuery()->getResult();
    }
}
