<?php

namespace ApiBundle\Repository;

use ApiBundle\Entity\Calendar;
use ApiBundle\Entity\RoomType;

/**
 * CalendarRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CalendarRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Get the Calendar by Date Range
     *
     * @param \DateTime $from
     * @param \DateTime $to
     * @return Calendar[]
     */
    public function findByDateRange(\DateTime $from, \DateTime $to)
    {
        $qb = $this->createQueryBuilder('c')
            ->where('c.day BETWEEN :from AND :to')
            ->setParameter('from', $from->format('Y-m-d'))
            ->setParameter('to', $to->format('Y-m-d'));

        return $qb->getQuery()->getResult();
    }

    /**
     * Get the Calendar by RoomType and Date Range
     *
     * @param RoomType $roomType
     * @param \DateTime $from
     * @param \DateTime $to
     * @return Calendar[]
     */
    public function findByRoomTypeAndDateRange(RoomType $roomType, \DateTime $from, \DateTime $to)
    {
        $qb = $this->createQueryBuilder('c')
            ->where('c.roomType = :roomType')
            ->andWhere('c.day BETWEEN :from AND :to')
            ->setParameter('roomType', $roomType)
            ->setParameter('from', $from->format('Y-m-d'))
            ->setParameter('to', $to->format('Y-m-d'));

        return $qb->getQuery()->getResult();
    }

    /**
     * Find a single calendar entity based on Room Type and Date
     *
     * @param RoomType $roomType
     * @param \DateTime $date
     * @return Calendar|null
     */
    public function findOneByRoomTypeAndDate(RoomType $roomType, \DateTime $date)
    {
        $qb = $this->createQueryBuilder('c')
            ->where('c.roomType = :roomType')
            ->andWhere('c.day = :date')
            ->setParameter('roomType', $roomType)
            ->setParameter('date', $date->format('Y-m-d'));

        return $qb->getQuery()->getOneOrNullResult();
    }
}
