<?php

namespace ApiBundle\Repository;

use ApiBundle\Entity\RoomType;

/**
 * RoomTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RoomTypeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Find a Room Type by Type
     *
     * @param string $type
     * @return RoomType|null
     */
    public function findOneByType($type)
    {
        $qb = $this->createQueryBuilder('r')
            ->where('r.type = :type')
            ->setParameter('type', $type);

        return $qb->getQuery()->getOneOrNullResult();
    }
}
